2018_CISCN_半决赛_华北赛区/web6/store/urls.py
from django.conf.urls import include, url
from store.views import *


urlpatterns = [
    #url(r'^$', index, name='index'),
    url(r'^$', index, name='index'),
    url(r'^products/$', products, name='products'),
    url(r'^info/(?P<cloid>[0-9]+)$', info, name='info'),
    url(r'^register$', do_reg, name='register'),
    url(r'^login$', do_login, name='login'),
    url(r'^login/$', do_login, name='login'),
    url(r'^logout/$', do_logout, name='logout'),
    url(r'^shopcar$', pay_car, name='view_cart'),
    url(r'^shopcar/add$', add_cart, name='add_cart'),
    url(r'^clean_cart/$', cleanCart, name='clean_cart'),
    url(r'^user$', userinfo, name='user'),
    url(r'^shop$', shoplist, name='shop'),
    url(r'^paycar$', pay_car, name='paycar'),
    url(r'^buydetails$', tobuydetails, name='buydetails'),
    url(r'^pay$', pay, name='pay'),
    url(r'^user/change$',changepass,name='changepass'),
    url(r'^pass/reset$',resetpass,name='resetpass'),
    url(r'^seckill$',seckill,name='seckill'),
    url(r'^search$',search,name='search'),
]

2018_CISCN_半决赛_华北赛区/web6/storeproject/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from store.views import *
from django.conf.urls.static import static

urlpatterns = [
    url(r'^xjnuonepiecedetective/', include(admin.site.urls)),
    url(r'^', include('store.urls')),
    url(r"^uploads/(?P<path>.*)$", \
                "django.views.static.serve", \
                {"document_root": settings.MEDIA_ROOT,}),
 ]+ static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

2018_CISCN_半决赛_华北赛区/web6/store/models.py
# coding: utf-8
from django.db import models
from django.contrib.auth.models import AbstractUser
import json

#用户
class User(AbstractUser):
    invite_user = models.CharField(max_length=50,null=True, unique=False, verbose_name='推荐人')
    integral = models.FloatField(default=1000.0,blank=True,null=False,verbose_name="点数")

    class Meta:
        verbose_name = '用户'
        verbose_name_plural = verbose_name
        ordering = ['-id']

    def __str__(self):
        return self.username

#西域美食
class Clothing(models.Model):
    name = models.CharField(max_length=150, verbose_name='名称')
    size = models.CharField(default="大份",max_length=7, verbose_name='分量')
    old_price = models.FloatField(default=0.0, verbose_name='原价')
    price = models.FloatField(default=0.0, verbose_name='价格')
    discount = models.FloatField(default=1, verbose_name='折扣')
    sales = models.IntegerField(default=0, verbose_name='销量')
    num = models.IntegerField(default=0, verbose_name='库存')
    details = models.CharField(max_length=100,default="", verbose_name='详情')
    image_url_i = models.ImageField(upload_to='meishi/%Y/%m', default= 'meishi/yangrouchuan.jpg', verbose_name='展示图片路径')
    image_url_l = models.ImageField(upload_to='meishi/%Y/%m', default= 'meishi/yangrouchuan.jpg', verbose_name='详情图片路径1')
    image_url_m = models.ImageField(upload_to='meishi/%Y/%m', default= 'meishi/yangrouchuan.jpg', verbose_name='详情图片路径2')
    image_url_r = models.ImageField(upload_to='meishi/%Y/%m', default= 'meishi/yangrouchuan.jpg', verbose_name='详情图片路径3')
    image_url_c = models.ImageField(upload_to='meishi/%Y/%m', default= 'meishi/yangrouchuan.jpg', verbose_name='购物车展示图片')

    class Meta:
        verbose_name = '商品'
        verbose_name_plural = verbose_name
        ordering = ['id']

    def __str__(self):
        return self.name + "---" + str(self.price)

#购买记录
class Buydetails(models.Model):
    user=models.ForeignKey(User,verbose_name='购买者')
    clothing=models.ForeignKey(Clothing,verbose_name="购买的商品")
    datat=models.DateTimeField(auto_now=True,verbose_name="购买时间")
    buynum=models.IntegerField(default=0,verbose_name="购买数量")
    buypay=models.IntegerField(default=0,verbose_name="购买价格")
    class Meta:
        verbose_name = '购买记录'
        verbose_name_plural = verbose_name
        ordering = ['id']

    def __str__(self):
        return self.user.username+"购买的"+self.clothing.name

#购物车条目
class Caritem(models.Model):
    clothing = models.ForeignKey(Clothing, verbose_name='购物车中产品条目')
    quantity = models.IntegerField(default=0, verbose_name='数量')
    sum_price = models.FloatField(default=0.0, verbose_name='小计')

    class Meta:
        verbose_name = '购物车条目'
        verbose_name_plural = verbose_name

    def __str__(self):
        return str(self.id)

#购物车
class Cart(object):
    def __init__(self):
        self.items = []
        self.total_price = 0.0

    def add(self, clothing):
        self.total_price += clothing.price
        plused=False
        for item in self.items:
            if item.clothing.id == clothing.id:
                item.quantity += 1
                item.sum_price += clothing.price
                plused=True
                break
        if not plused:
            self.items.append(Caritem(clothing=clothing, quantity=1, sum_price=clothing.price))

2018_CISCN_半决赛_华北赛区/web6/store/forms.py
#coding:utf-8
from django import forms

#登录表单
class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={"placeholder": "用户名", "required": "required",}),
                              max_length=50,error_messages={"required": "username不能为空",})
    password = forms.CharField(widget=forms.PasswordInput(attrs={"placeholder": "密码", "required": "required",}),
                              max_length=20,error_messages={"required": "password不能为空",})

#修改密码表单
class ChangePassForm(forms.Form):
    old_password = forms.CharField(widget=forms.PasswordInput(attrs={"placeholder": "旧密码", "required": "required",}),
                              max_length=20,error_messages={"required": "password不能为空",})
    password = forms.CharField(widget=forms.PasswordInput(attrs={"placeholder": "密码", "required": "required",}),
                              max_length=20,error_messages={"required": "password不能为空",})
    password_confirm = forms.CharField(widget=forms.PasswordInput(attrs={"placeholder": "确认密码", "required": "required",}),
                              max_length=20,error_messages={"required": "password不能为空",})
    def clean(self):
        if self.cleaned_data['password_confirm'] != self.cleaned_data['password']:
            raise forms.ValidationError('两次输入密码不一致')
        else:
            cleaned_data = super(ChangePassForm,self).clean()
        return cleaned_data

#注册表单
class RegForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={"placeholder": "用户名", "required": "required",}),
                              max_length=50,error_messages={"required": "username不能为空",})
    mail = forms.EmailField(widget=forms.TextInput(attrs={"placeholder": "邮箱", "required": "required",}),
                              max_length=50,error_messages={"required": "email不能为空",})
    #invite_user = forms.CharField(widget=forms.TextInput(attrs={"placeholder": "推荐人", }),
    #                           max_length=20,)
    password = forms.CharField(widget=forms.PasswordInput(attrs={"placeholder": "密码", "required": "required",}),
                              max_length=20,error_messages={"required": "password不能为空",})
    password_confirm = forms.CharField(widget=forms.PasswordInput(attrs={"placeholder": "确认密码", "required": "required",}),
                              max_length=20,error_messages={"required": "password不能为空",})

    def clean(self):
        if self.cleaned_data['password_confirm'] != self.cleaned_data['password']:
            raise forms.ValidationError('两次输入密码不一致')
        else:
            cleaned_data = super(RegForm,self).clean()
        return cleaned_data

#评论表单
class CommentForm(forms.Form):
    author = forms.CharField(widget=forms.TextInput(attrs={"id":"author","class":"comment_input",
                                                           "required":"required","size":"25",
                                                           "tabindex":"1"}),
                             max_length=50,error_messages={"required":"username不能为空",})

    email = forms.EmailField(widget=forms.TextInput(attrs={"id":"email","type":"email",
                                                           "class": "comment_input",
                                                           "required":"required","size":"25",
                                                           "tabindex":"2"}),
                                 max_length=50, error_messages={"required":"email不能为空",})

    url = forms.URLField(widget=forms.TextInput(attrs={"id":"url","type":"url","class": "comment_input",
                                                       "size":"25", "tabindex":"3"}),
                              max_length=100, required=False)

    comment = forms.CharField(widget=forms.Textarea(attrs={"id":"comment","class": "message_input",
                                                           "required": "required", "cols": "25",
                                                           "rows": "5", "tabindex": "4"}),
                                                    error_messages={"required":"评论不能为空",})

    article = forms.CharField(widget=forms.HiddenInput())

2018_CISCN_半决赛_华北赛区/web6/templates/ad.html
{% load staticfiles %}
<div class="banner">
    <div class="col-sm-3 banner-mat">
        <img class="img-responsive"	src="{% static 'images/kaobaozi.jpg' %}" alt="">
    </div>
    <div class="col-sm-6 matter-banner">
        <div class="slider">
            <div class="callbacks_container">
                <ul class="rslides" id="slider">
                    <li>
                        <img class="img-responsive"	src="{% static 'images/nangmiddle.jpg' %}" alt="">
                     </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="col-sm-3 banner-mat">
        <img class="img-responsive" src="{% static 'images/dapanji.jpg' %}" alt="">
    </div>
    <div class="clearfix"> </div>
    </div>

2018_CISCN_半决赛_华北赛区/web6/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <title>西域美食</title>
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" type="text/css" media="all" />
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <!-- Custom Theme files -->
    <!--theme-style-->
    <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css" media="all" />
    <!--//theme-style-->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="Fashion Mania Responsive web template, Bootstrap Web Templates, Flat Web Templates, Andriod Compatible web template,
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design" />
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    <!-- start menu -->
    <link href="{% static 'css/memenu.css' %}" rel="stylesheet" type="text/css" media="all" />
    <script type="text/javascript" src="{% static 'js/memenu.js' %}"></script>
    <script>$(document).ready(function(){$(".memenu").memenu();});</script>
    <script src="{% static 'js/simpleCart.min.js' %}"> </script>
    <!-- slide -->
    <script src="{% static 'js/responsiveslides.min.js' %}"></script>
    <script>
        $(function () {
            $("#slider").responsiveSlides({
                auto: true,
                speed: 500,
                namespace: "callbacks",
                pager: true
            });
        });
    </script>
</head>
<body>
<!--header-->
<div class="header">
<div class="header-top">
    <div class="container">
        <div class="col-sm-4 world">
        </div>
        <div class="col-sm-4 logo">
            <a href="/"><img src="{% static 'images/logo.jpg' %}" alt=""></a>
        </div>

        <div class="col-sm-4 header-left">
            {% if not request.user.is_authenticated %}
                <p class="log"><a href="{% url 'login' %}"  >登录</a>
                <span>|</span>
                <a  href="{% url 'register' %}"  >注册</a></p>
            {% else %}
                <p class="log"><a href="{% url 'user' %}"  >{{ request.user.username }}</a>
                <span>|</span>
                <a  href="{% url 'logout' %}"  >退出</a></p>
            {% endif %}
            <div class="cart box_1">
                <a href="{% url 'view_cart' %}">
                    <h3>
                        <div class="total">
                            {% if request.user.is_authenticated %}
                                {% if cart.total_price %}
                                    <span>{{ cart.total_price }}元</span>
                                {% else %}
                                    <span>0.0元</span>
                                {% endif %}
                            {% else %}
                                <span>0.0元</span>
                            {% endif %}
                        </div>
                        <img src="{% static 'images/cart.png' %}" alt=""/></h3>
                </a>
                <p><a href="{% url 'clean_cart' %}" class="simpleCart_empty">清空购物车</a></p>

            </div>
            <div class="clearfix"> </div>
        </div>
        <div class="clearfix"> </div>
    </div>
</div>
<div class="container">
    <div class="head-top">
        <div class="col-sm-2 number">
        </div>
        <div class="col-sm-8 h_menu4">
            <ul class="memenu skyblue">
                <li class=" grid"><a  href="{% url 'index' %}">主页</a></li>
                <li><a  href="#">干果</a>
                    <div class="mepanel">
                        <div class="row">
                            <div class="col1">
                                <div class="h_nav">
                                    <h4>巴旦木</h4>
                                </div>
                            </div>
                            <div class="col1">
                                <div class="h_nav">
                                    <h4>核桃</h4>
                                </div>
                            </div>
                            <div class="col1">
                                <div class="h_nav">
                                    <h4>红枣</h4>
                                    <ul>
                                        {% for brand in brand_list %}
                                            <li><a href="{% url 'brands' %}?bid={{ brand.id }}">{{ brand.name }}</a></li>
                                        {% endfor %}
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </li>
                <li class="grid"><a  href="#">美食</a>
                    <div class="mepanel">
                        <div class="row">
                            <div class="col1">
                                <div class="h_nav">
                                    <h4>大盘鸡</h4>
                                </div>
                            </div>
                            <div class="col1">
                                <div class="h_nav">
                                    <h4>羊肉串</h4>
                                </div>
                            </div>
                            <div class="col1">
                                <div class="h_nav">
                                    <h4>烤包子</h4>
                                </div>
                            </div>
                        </div>
                    </div>
                </li>
                <li><a  href="{% url 'shop' %}">美食列表</a></li>
            </ul>
        </div>
        <div class="clearfix"> </div>
        <!---pop-up-box---->
{#        <script type="text/javascript" src="js/modernizr.custom.min.js"></script>#}
        <link href="{% static 'css/popuo-box.css' %}" rel="stylesheet" type="text/css" media="all"/>
        <script src="{% static 'js/jquery.magnific-popup.js' %}" type="text/javascript"></script>
        <!---//pop-up-box---->
        <script>
            $(document).ready(function() {
                $('.popup-with-zoom-anim').magnificPopup({
                    type: 'inline',
                    fixedContentPos: false,
                    fixedBgPos: true,
                    overflowY: 'auto',
                    closeBtnInside: true,
                    preloader: false,
                    midClick: true,
                    removalDelay: 300,
                    mainClass: 'my-mfp-zoom-in'
                });

            });
        </script>
        <!---->
    </div>
</div>
</div>
<!--banner-->
{% block banner_block %}{% endblock %}
<!--//banner-->
<!--content-->
{% block content_block %}{% endblock %}
<!--//content-->
<!--footer-->
<div class="footer">
    <div class="footer-bottom">
        <div class="container">
            <div class="clearfix"> </div>
            <p class="footer-class">Copyright &copy; 2018.Company name All rights reserved.<a target="_blank" href="https://github.com/Huseck">大象安服</a></p>
        </div>
    </div>
</div>
<!--//footer-->
</body>
</html>

2018_CISCN_半决赛_华北赛区/web6/templates/changepass.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content_block %}
    <div class="content">
    <div class="container">
        <div class="content-top">
            <h1>修改密码</h1>
            {% for message in messages %}
              <div class="ui positive message">
              <div class="alert alert-success alert-dismissable">
                {{ message }}
              </div>
              </div>
              {% endfor %}
            <div class="content-top1 col-md-6 login-right ">
           <form action="{% url 'changepass' %}" method="post">
                    {% csrf_token %}
					    <span>旧密码</span>
					    {{ changePass_form.old_password }}

					    <span>新密码</span>
					    {{ changePass_form.password }}

                        <span>重复密码</span>
					    {{ changePass_form.password_confirm }}
					<div class="word-in">
                        <input type="hidden" name="source_url" value="{{ request.META.HTTP_REFERER }}">
				 		<input type="submit" value="修改密码">
				  	</div>
			    </form>
            </div>
    </div>
    </div>
    {% include 'pagination.html' %}
    </div>
    </div>
{% endblock %}

2018_CISCN_半决赛_华北赛区/web6/templates/checkout.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content_block %}
<div class="container">
	<div class="check-out">
		<h1>购物车</h1>
    {% for message in messages %}
              <div class="ui negative message">
              <div class="alert alert-danger alert-dismissable">
                {{ message }}
              </div>
              </div>
              {% endfor %}
    	  <table >
		  <tr>
			<th>商品</th>
			<th>数量</th>
			<th>原价</th>
			<th>现价</th>
			<th>小计</th>
		  </tr>
          <div class="shopcar_list">
          {% for item in cart.items %}
		  <tr>
			<td class="ring-in"><a href="{% url 'info' item.clothing.id%}" class="at-in"><img src="{{ MEDIA_URL }}{{ item.clothing.image_url_c }}" class="img-responsive" alt=""></a>

                <div class="sed">
				<h5>{{ item.clothing.name }}</h5>
				<p>{{ item.clothing.desc }}</p>
			</div>
			<div class="clearfix "> </div></td>
			<td class="check"><input type="text" value="{{ item.quantity }}" readonly="readonly"></td>
			<td style="text-decoration:line-through">{{ item.clothing.old_price }}元</td>
			<td>{{ item.clothing.price }}元</td>
			<td>{{ item.sum_price }}元</td>
		  </tr>
          {% endfor %}
          </div>
          <tr>
              <form action="{% url 'paycar' %}" method="post" id="paycar">
                            {% csrf_token %}
                            <input type="hidden" name="price" value="{{ cart.total_price }}">
                            <a href="#" class="to-buy" onclick="document.getElementById('paycar').submit();">去结算</a>
                         </form>
          &nbsp;&nbsp;&nbsp;总价：{{ cart.total_price }}元</td>
          </tr>
	</table>
{#	<a href="#" class=" to-buy">去结算</a>#}
	<div class="clearfix"> </div>
    </div>
</div>
{% endblock %}

2018_CISCN_半决赛_华北赛区/web6/templates/error.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content_block %}
        <div class="content">
    <div class="container">
        <div class="content-top">
            <h1>{{ reason }}</h1>
        </div>
    </div>
    </div>
{% endblock %}

2018_CISCN_半决赛_华北赛区/web6/templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block banner_block %}
    {% include 'ad.html' %}
{% endblock %}
{% block content_block %}
    <div class="content">
    <div class="container">
        <div class="content-top">
            <h1>最新商品</h1>
            <div class="content-top1">
                {% for clo in clo_list %}
               <form action="{% url 'add_cart'%}" method="post" id="subform{{ clo.id }}">
                {% csrf_token %}
                     <input type="hidden" name="id" value="{{ clo.id }}">
                     </form>
                <div class="col-md-3 col-md2">
                        <div class="col-md1 simpleCart_shelfItem">
                            <a href="{% url 'info' clo.id %}">
                                <img class="img-responsive" src="{{ MEDIA_URL }}{{ clo.image_url_i }}" alt="" />
                            </a>
                            <h3><a href="{% url 'info' clo.id%}">{{ clo.brand.name }}</a></h3>
                            <div class="price">
                                    <h5 class="item_price">{{ clo.price }}元</h5>


                                    <a href="#" class="item_add" onclick="document.getElementById('subform{{ clo.id }}').submit();">放入购物车</a>

                                    <div class="clearfix"> </div>
                            </div>
                        </div>
                </div>
                {% endfor %}
            <div class="clearfix"> </div>
            </div>
        </div>
    {% include 'pagination.html' %}
    </div>
    </div>
{% endblock %}

2018_CISCN_半决赛_华北赛区/web6/templates/list.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content_block %}
    <div class="content">
    <div class="container">
        <div class="content-top">
            <h1>最新商品</h1>
        {% if user.is_superuser %}
         <form action="{% url 'search'%}" method="get" id="search{{ clo.id }}">
                    {% csrf_token %}
                    <input type="text" name="searchstr" value="{{ clo.id }}">
                    <a href="#"  onclick="document.getElementById('search{{ clo.id }}').submit();">搜索商品</a>
                    </form>
            <div class="results-str">{{ coutstr }}</div>
        {% endif %}

            <div class="content-top1 commodity-list">
                {% for clo in clo_list %}
                <form action="{% url 'add_cart'%}" method="post" id="subform{{ clo.id }}">
                {% csrf_token %}
                     <input type="hidden" name="id" value="{{ clo.id }}">
                     </form>
                    <form action="{% url 'seckill'%}" method="post" id="seckill{{ clo.id }}">
                    {% csrf_token %}
                    <input type="hidden" name="id" value="{{ clo.id }}">
                    </form>
                <div class="col-md-3 col-md2">
                        <div class="col-md1 simpleCart_shelfItem">
                            <a href="{% url 'info' clo.id%}">
                                <img class="img-responsive" src="{{ MEDIA_URL }}{{ clo.image_url_i }}" alt="" />
                            </a>
                            <h3><a href="{% url 'info' clo.id%}">数量:{{ clo.num }}</a></h3>
                            <div class="price">
                                    <h5 class="item_price">{{ clo.price }}元</h5>

                                    <a href="#" class="item_add" onclick="document.getElementById('subform{{ clo.id }}').submit();">放入购物车</a>
                                    <a href="#"  onclick="document.getElementById('seckill{{ clo.id }}').submit();">秒杀</a>
                                    <div class="clearfix"> </div>
                            </div>
                        </div>
                </div>


                {% endfor %}
            <div class="clearfix"> </div>
            </div>
        </div>
    {% include 'pagination.html' %}
    </div>
    </div>
{% endblock %}

2018_CISCN_半决赛_华北赛区/web6/templates/register.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content_block %}
    <script>
window.onload = function () {
var c = document.getElementById("vtt_captcha");
var ctx = c.getContext("2d");
var img = new Image();
img.onload = function () {
ctx.drawImage(img, 0, 0);
};
img.src = '{{ cap.jpg }}';
c.onmousedown = function (event) {
var rect = this.getBoundingClientRect();
var x = (event.x - rect.left) * (this.width / rect.width);
var y = (event.y - rect.top) * (this.height / rect.height);
ctx = c.getContext("2d");
ctx.beginPath();
ctx.arc(x,y,10,0,360,false);
ctx.fillStyle="red";
ctx.fill();
ctx.closePath();
document.getElementById('captcha_x').value = x;
document.getElementById('captcha_y').value = y;
}
};
</script>
<div class="container">
	<div class="register">
		<h1>注册</h1>
                     {% for message in messages %}
              <div class="ui negative message">
              <div id=""class="alert alert-danger alert-dismissable">
                {{ message }}
            </div>
              </div>
              {% endfor %}
		  	  <form action="{% url 'register' %}" method="post">

                 {% csrf_token %}
				 <div class="col-md-6  register-top-grid">
					<div class="mation">
						<span>用户名</span>
						{{ reg_form.username }}

						 <span>邮箱</span>
						 {{ reg_form.mail }}
                         <span>推荐人</span>
						 <input id="id_invite_user" maxlength="20" name="invite_user" placeholder="推荐人" type="text" />
                        <div>
                            <label>验证码 ( {{ cap.question }} )：</label><br/>
                            <canvas id="vtt_captcha" width="680" height="460" rel="{{ cap.uuid }}"></canvas>
                            <input type="hidden" id="" name="picid" value="{{ cap.uuid }}">
                            <input type="hidden" id="captcha_x" name="captcha_x" value="">
                            <input type="hidden" id="captcha_y" name="captcha_y" value="">
                        </div>
					</div>
					 <div class="clearfix"> </div>
                 </div>
                 <div class=" col-md-6 register-bottom-grid">
                    <div class="mation">
                        <span>密码</span>
                        {{ reg_form.password }}
                        <span>确认密码</span>
                        {{ reg_form.password_confirm }}
                    </div>
                 </div>
                 <div class="clearfix"> </div>
                  <div class="register-but">
                       <input type="hidden" name="source_url" value="{{ request.META.HTTP_REFERER }}">
                      <input type="submit" value="submit">
                      <div class="clearfix"> </div>
				  </div>
              </form>
    </div>
</div>
{% endblock %}

2018_CISCN_半决赛_华北赛区/web6/templates/resetpass.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content_block %}
        <script>
window.onload = function () {
var c = document.getElementById("vtt_captcha");
var ctx = c.getContext("2d");
var img = new Image();
img.onload = function () {
ctx.drawImage(img, 0, 0);
};
img.src = '{{ cap.jpg }}';
c.onmousedown = function (event) {
var rect = this.getBoundingClientRect();
var x = (event.x - rect.left) * (this.width / rect.width);
var y = (event.y - rect.top) * (this.height / rect.height);
ctx = c.getContext("2d");
ctx.beginPath();
ctx.arc(x,y,10,0,360,false);
ctx.fillStyle="red";
ctx.fill();
ctx.closePath();
document.getElementById('captcha_x').value = x;
document.getElementById('captcha_y').value = y;
}
};
</script>
    <div class="content">
    <div class="container">
        <div class="content-top">
            {% for message in messages %}
              <div class="ui positive message">
              <div class="alert alert-success alert-dismissable">
                {{ message }}
              </div>
              </div>
              {% endfor %}
            <h1>重置密码</h1>
            <div class="content-top1 col-md-6 login-right ">
           <form action="{% url 'resetpass' %}" method="post">
                    {% csrf_token %}
					<span>邮箱</span>
					<input id="id_mail" maxlength="50" name="mail" placeholder="邮箱" required="required" type="text" />
<div>
<label>验证码 ( {{ cap.question }} )：</label><br/>
<canvas id="vtt_captcha" width="680" height="460" rel="{{ cap.uuid }}"></canvas>
    <input type="hidden" id="" name="picid" value="{{ cap.uuid }}">
<input type="hidden" id="captcha_x" name="captcha_x" value="">
<input type="hidden" id="captcha_y" name="captcha_y" value="">
</div>
					<div class="word-in">
                        <input type="hidden" name="source_url" value="{{ request.META.HTTP_REFERER }}">
				 		<input type="submit" value="重置密码">
				  	</div>
			    </form>
            </div>
    </div>
    </div>
    {% include 'pagination.html' %}
    </div>
    </div>
{% endblock %}